# Generated by Django 5.2 on 2025-04-21 21:11

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models

import apps.users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Email уже занят'}, help_text='Укажите действующий email (максимум 254 символа). Будет использоваться для входа в систему.', max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('username', models.CharField(error_messages={'unique': 'Логин уже занят'}, help_text='Укажите уникальный логин (максимум 30 символов). Допустимы только буквы, цифры и символы @/./+/-/_.', max_length=30, unique=True, validators=[apps.users.validators.validate_username], verbose_name='Логин')),
                ('first_name', models.CharField(blank=True, help_text='Укажите ваше имя (необязательно, максимум 50 символов)', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Укажите вашу фамилию (необязательно, максимум 50 символов)', max_length=50, verbose_name='Фамилия')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'объект "Пользователь"',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
